context:
  name: curvlinops-for-pytorch
  version: "3.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/curvlinops_for_pytorch-${{ version }}.tar.gz
  sha256: 52ff661821147705f66a981ea090c750ad9e4c741c06f46d8282c5e63c776066

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - backpack-for-pytorch >=1.6.0,<2.0.0
    - pytorch >=2.0
    - scipy >=1.7.1,<2.0.0
    - tqdm >=4.61.0,<5.0.0
    - einops
    - einconv
    - numpy <2

tests:
  - python:
      imports:
        - curvlinops
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: scipy Linear operators for curvature matrices in PyTorch
  homepage: https://github.com/f-dangel/curvlinops
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
